/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CharacterSummary 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5642126254447564945L;
    private String name;
    private String resourceURI;
    private String role;
    /** GETTER
     * The full name of the character.
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * The full name of the character.
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * The path to the individual character resource.
     */
    @JsonGetter("resourceURI")
    public String getResourceURI ( ) { 
        return this.resourceURI;
    }
    
    /** SETTER
     * The path to the individual character resource.
     */
    @JsonSetter("resourceURI")
    public void setResourceURI (String value) { 
        this.resourceURI = value;
    }
 
    /** GETTER
     * The role of the creator in the parent entity.
     */
    @JsonGetter("role")
    public String getRole ( ) { 
        return this.role;
    }
    
    /** SETTER
     * The role of the creator in the parent entity.
     */
    @JsonSetter("role")
    public void setRole (String value) { 
        this.role = value;
    }
 
}
 