/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class ComicListBuilder {
    //the instance to build
    private ComicList comicList;

    /**
     * Default constructor to initialize the instance
     */
    public ComicListBuilder() {
        comicList = new ComicList();
    }

    /**
     * The number of total available issues in this list. Will always be greater than or equal to the "returned" value.
     */
    public ComicListBuilder available(int available) {
        comicList.setAvailable(available);
        return this;
    }

    /**
     * The path to the full list of issues in this collection.
     */
    public ComicListBuilder collectionURI(String collectionURI) {
        comicList.setCollectionURI(collectionURI);
        return this;
    }

    /**
     * The list of returned issues in this collection.
     */
    public ComicListBuilder items(List<ComicSummary> items) {
        comicList.setItems(items);
        return this;
    }

    /**
     * The number of issues returned in this collection (up to 20).
     */
    public ComicListBuilder returned(int returned) {
        comicList.setReturned(returned);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ComicList build() {
        return comicList;
    }
}