/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ComicDate 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5431069337296296002L;
    private Date date;
    private String type;
    /** GETTER
     * The date.
     */
    @JsonGetter("date")
    public Date getDate ( ) { 
        return this.date;
    }
    
    /** SETTER
     * The date.
     */
    @JsonSetter("date")
    public void setDate (Date value) { 
        this.date = value;
    }
 
    /** GETTER
     * A description of the date (e.g. onsale date, FOC date).
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * A description of the date (e.g. onsale date, FOC date).
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
}
 