/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class ComicDataContainerBuilder {
    //the instance to build
    private ComicDataContainer comicDataContainer;

    /**
     * Default constructor to initialize the instance
     */
    public ComicDataContainerBuilder() {
        comicDataContainer = new ComicDataContainer();
    }

    /**
     * The total number of results returned by this call.
     */
    public ComicDataContainerBuilder count(int count) {
        comicDataContainer.setCount(count);
        return this;
    }

    /**
     * The requested result limit.
     */
    public ComicDataContainerBuilder limit(int limit) {
        comicDataContainer.setLimit(limit);
        return this;
    }

    /**
     * The requested offset (number of skipped results) of the call.
     */
    public ComicDataContainerBuilder offset(int offset) {
        comicDataContainer.setOffset(offset);
        return this;
    }

    /**
     * The list of comics returned by the call
     */
    public ComicDataContainerBuilder results(List<Comic> results) {
        comicDataContainer.setResults(results);
        return this;
    }

    /**
     * The total number of resources available given the current filter set.
     */
    public ComicDataContainerBuilder total(int total) {
        comicDataContainer.setTotal(total);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ComicDataContainer build() {
        return comicDataContainer;
    }
}