/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class ComicDateBuilder {
    //the instance to build
    private ComicDate comicDate;

    /**
     * Default constructor to initialize the instance
     */
    public ComicDateBuilder() {
        comicDate = new ComicDate();
    }

    /**
     * The date.
     */
    public ComicDateBuilder date(Date date) {
        comicDate.setDate(date);
        return this;
    }

    /**
     * A description of the date (e.g. onsale date, FOC date).
     */
    public ComicDateBuilder type(String type) {
        comicDate.setType(type);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ComicDate build() {
        return comicDate;
    }
}