/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class CreatorDataContainerBuilder {
    //the instance to build
    private CreatorDataContainer creatorDataContainer;

    /**
     * Default constructor to initialize the instance
     */
    public CreatorDataContainerBuilder() {
        creatorDataContainer = new CreatorDataContainer();
    }

    /**
     * The total number of results returned by this call.
     */
    public CreatorDataContainerBuilder count(int count) {
        creatorDataContainer.setCount(count);
        return this;
    }

    /**
     * The requested result limit.
     */
    public CreatorDataContainerBuilder limit(int limit) {
        creatorDataContainer.setLimit(limit);
        return this;
    }

    /**
     * The requested offset (number of skipped results) of the call.
     */
    public CreatorDataContainerBuilder offset(int offset) {
        creatorDataContainer.setOffset(offset);
        return this;
    }

    /**
     * The list of creators returned by the call.
     */
    public CreatorDataContainerBuilder results(List<Creator> results) {
        creatorDataContainer.setResults(results);
        return this;
    }

    /**
     * The total number of resources available given the current filter set.
     */
    public CreatorDataContainerBuilder total(int total) {
        creatorDataContainer.setTotal(total);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreatorDataContainer build() {
        return creatorDataContainer;
    }
}