/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class CreatorSummaryBuilder {
    //the instance to build
    private CreatorSummary creatorSummary;

    /**
     * Default constructor to initialize the instance
     */
    public CreatorSummaryBuilder() {
        creatorSummary = new CreatorSummary();
    }

    /**
     * The full name of the creator.
     */
    public CreatorSummaryBuilder name(String name) {
        creatorSummary.setName(name);
        return this;
    }

    /**
     * The path to the individual creator resource.
     */
    public CreatorSummaryBuilder resourceURI(String resourceURI) {
        creatorSummary.setResourceURI(resourceURI);
        return this;
    }

    /**
     * The role of the creator in the parent entity.
     */
    public CreatorSummaryBuilder role(String role) {
        creatorSummary.setRole(role);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreatorSummary build() {
        return creatorSummary;
    }
}