/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class CreatorListBuilder {
    //the instance to build
    private CreatorList creatorList;

    /**
     * Default constructor to initialize the instance
     */
    public CreatorListBuilder() {
        creatorList = new CreatorList();
    }

    /**
     * The number of total available creators in this list. Will always be greater than or equal to the "returned" value.
     */
    public CreatorListBuilder available(int available) {
        creatorList.setAvailable(available);
        return this;
    }

    /**
     * The path to the full list of creators in this collection.
     */
    public CreatorListBuilder collectionURI(String collectionURI) {
        creatorList.setCollectionURI(collectionURI);
        return this;
    }

    /**
     * The list of returned creators in this collection.
     */
    public CreatorListBuilder items(List<CreatorSummary> items) {
        creatorList.setItems(items);
        return this;
    }

    /**
     * The number of creators returned in this collection (up to 20).
     */
    public CreatorListBuilder returned(int returned) {
        creatorList.setReturned(returned);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreatorList build() {
        return creatorList;
    }
}