/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class CreatorBuilder {
    //the instance to build
    private Creator creator;

    /**
     * Default constructor to initialize the instance
     */
    public CreatorBuilder() {
        creator = new Creator();
    }

    /**
     * A resource list containing the comics which feature work by this creator.
     */
    public CreatorBuilder comics(ComicList comics) {
        creator.setComics(comics);
        return this;
    }

    /**
     * A resource list containing the events which feature work by this creator.
     */
    public CreatorBuilder events(EventList events) {
        creator.setEvents(events);
        return this;
    }

    /**
     * The first name of the creator.
     */
    public CreatorBuilder firstName(String firstName) {
        creator.setFirstName(firstName);
        return this;
    }

    /**
     * The full name of the creator (a space-separated concatenation of the above four fields).
     */
    public CreatorBuilder fullName(String fullName) {
        creator.setFullName(fullName);
        return this;
    }

    /**
     * The unique ID of the creator resource.
     */
    public CreatorBuilder id(int id) {
        creator.setId(id);
        return this;
    }

    /**
     * The last name of the creator.
     */
    public CreatorBuilder lastName(String lastName) {
        creator.setLastName(lastName);
        return this;
    }

    /**
     * The middle name of the creator.
     */
    public CreatorBuilder middleName(String middleName) {
        creator.setMiddleName(middleName);
        return this;
    }

    /**
     * The date the resource was most recently modified.
     */
    public CreatorBuilder modified(Date modified) {
        creator.setModified(modified);
        return this;
    }

    /**
     * The canonical URL identifier for this resource.
     */
    public CreatorBuilder resourceURI(String resourceURI) {
        creator.setResourceURI(resourceURI);
        return this;
    }

    /**
     * A resource list containing the series which feature work by this creator.
     */
    public CreatorBuilder series(SeriesList series) {
        creator.setSeries(series);
        return this;
    }

    /**
     * A resource list containing the stories which feature work by this creator.
     */
    public CreatorBuilder stories(StoryList stories) {
        creator.setStories(stories);
        return this;
    }

    /**
     * The suffix or honorific for the creator.
     */
    public CreatorBuilder suffix(String suffix) {
        creator.setSuffix(suffix);
        return this;
    }

    /**
     * The representative image for this creator.
     */
    public CreatorBuilder thumbnail(Thumbnail thumbnail) {
        creator.setThumbnail(thumbnail);
        return this;
    }

    /**
     * A set of public web site URLs for the resource.
     */
    public CreatorBuilder urls(List<Url> urls) {
        creator.setUrls(urls);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Creator build() {
        return creator;
    }
}