/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class CreatorDataWrapperBuilder {
    //the instance to build
    private CreatorDataWrapper creatorDataWrapper;

    /**
     * Default constructor to initialize the instance
     */
    public CreatorDataWrapperBuilder() {
        creatorDataWrapper = new CreatorDataWrapper();
    }

    /**
     * An HTML representation of the attribution notice for this result.  Please display either this notice or the contents of the attributionText field on all screens which contain data from the Marvel Comics API.
     */
    public CreatorDataWrapperBuilder attributionHTML(String attributionHTML) {
        creatorDataWrapper.setAttributionHTML(attributionHTML);
        return this;
    }

    /**
     * The attribution notice for this result.  Please display either this notice or the contents of the attributionHTML field on all screens which contain data from the Marvel Comics API.
     */
    public CreatorDataWrapperBuilder attributionText(String attributionText) {
        creatorDataWrapper.setAttributionText(attributionText);
        return this;
    }

    /**
     * The HTTP status code of the returned result.
     */
    public CreatorDataWrapperBuilder code(int code) {
        creatorDataWrapper.setCode(code);
        return this;
    }

    /**
     * The copyright notice for the returned result.
     */
    public CreatorDataWrapperBuilder copyright(String copyright) {
        creatorDataWrapper.setCopyright(copyright);
        return this;
    }

    /**
     * The results returned by the call.
     */
    public CreatorDataWrapperBuilder data(CreatorDataContainer data) {
        creatorDataWrapper.setData(data);
        return this;
    }

    /**
     * A digest value of the content returned by the call.
     */
    public CreatorDataWrapperBuilder etag(String etag) {
        creatorDataWrapper.setEtag(etag);
        return this;
    }

    /**
     * A string description of the call status.
     */
    public CreatorDataWrapperBuilder status(String status) {
        creatorDataWrapper.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreatorDataWrapper build() {
        return creatorDataWrapper;
    }
}