/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class EventListBuilder {
    //the instance to build
    private EventList eventList;

    /**
     * Default constructor to initialize the instance
     */
    public EventListBuilder() {
        eventList = new EventList();
    }

    /**
     * The number of total available events in this list. Will always be greater than or equal to the "returned" value.
     */
    public EventListBuilder available(int available) {
        eventList.setAvailable(available);
        return this;
    }

    /**
     * The path to the full list of events in this collection.
     */
    public EventListBuilder collectionURI(String collectionURI) {
        eventList.setCollectionURI(collectionURI);
        return this;
    }

    /**
     * The list of returned events in this collection.
     */
    public EventListBuilder items(List<EventSummary> items) {
        eventList.setItems(items);
        return this;
    }

    /**
     * The number of events returned in this collection (up to 20).
     */
    public EventListBuilder returned(int returned) {
        eventList.setReturned(returned);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public EventList build() {
        return eventList;
    }
}