/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class EventSummaryBuilder {
    //the instance to build
    private EventSummary eventSummary;

    /**
     * Default constructor to initialize the instance
     */
    public EventSummaryBuilder() {
        eventSummary = new EventSummary();
    }

    /**
     * The name of the event.
     */
    public EventSummaryBuilder name(String name) {
        eventSummary.setName(name);
        return this;
    }

    /**
     * The path to the individual event resource.
     */
    public EventSummaryBuilder resourceURI(String resourceURI) {
        eventSummary.setResourceURI(resourceURI);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public EventSummary build() {
        return eventSummary;
    }
}