/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class EventDataWrapperBuilder {
    //the instance to build
    private EventDataWrapper eventDataWrapper;

    /**
     * Default constructor to initialize the instance
     */
    public EventDataWrapperBuilder() {
        eventDataWrapper = new EventDataWrapper();
    }

    /**
     * An HTML representation of the attribution notice for this result.  Please display either this notice or the contents of the attributionText field on all screens which contain data from the Marvel Comics API.
     */
    public EventDataWrapperBuilder attributionHTML(String attributionHTML) {
        eventDataWrapper.setAttributionHTML(attributionHTML);
        return this;
    }

    /**
     * The attribution notice for this result.  Please display either this notice or the contents of the attributionHTML field on all screens which contain data from the Marvel Comics API.
     */
    public EventDataWrapperBuilder attributionText(String attributionText) {
        eventDataWrapper.setAttributionText(attributionText);
        return this;
    }

    /**
     * The HTTP status code of the returned result.
     */
    public EventDataWrapperBuilder code(int code) {
        eventDataWrapper.setCode(code);
        return this;
    }

    /**
     * The copyright notice for the returned result.
     */
    public EventDataWrapperBuilder copyright(String copyright) {
        eventDataWrapper.setCopyright(copyright);
        return this;
    }

    /**
     * The results returned by the call.
     */
    public EventDataWrapperBuilder data(EventDataContainer data) {
        eventDataWrapper.setData(data);
        return this;
    }

    /**
     * A digest value of the content returned by the call.
     */
    public EventDataWrapperBuilder etag(String etag) {
        eventDataWrapper.setEtag(etag);
        return this;
    }

    /**
     * A string description of the call status.
     */
    public EventDataWrapperBuilder status(String status) {
        eventDataWrapper.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public EventDataWrapper build() {
        return eventDataWrapper;
    }
}