/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum FormatTypeEnum {
    COLLECTION, //TODO: Write general description for this element
    COMIC; //TODO: Write general description for this element

    private static TreeMap<String, FormatTypeEnum> valueMap = new TreeMap<String, FormatTypeEnum>();
    private String value;

    static {
        COLLECTION.value = "collection";
        COMIC.value = "comic";

        valueMap.put("collection", COLLECTION);
        valueMap.put("comic", COMIC);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static FormatTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of FormatTypeEnum values to list of string values
     * @param toConvert The list of FormatTypeEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<FormatTypeEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (FormatTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 