/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class ImageBuilder {
    //the instance to build
    private Image image;

    /**
     * Default constructor to initialize the instance
     */
    public ImageBuilder() {
        image = new Image();
    }

    /**
     * The file extension for the image.
     */
    public ImageBuilder extension(String extension) {
        image.setExtension(extension);
        return this;
    }

    /**
     * The directory path of to the image.
     */
    public ImageBuilder path(String path) {
        image.setPath(path);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Image build() {
        return image;
    }
}