/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class SeriesSummaryBuilder {
    //the instance to build
    private SeriesSummary seriesSummary;

    /**
     * Default constructor to initialize the instance
     */
    public SeriesSummaryBuilder() {
        seriesSummary = new SeriesSummary();
    }

    /**
     * The canonical name of the series.
     */
    public SeriesSummaryBuilder name(String name) {
        seriesSummary.setName(name);
        return this;
    }

    /**
     * The path to the individual series resource.
     */
    public SeriesSummaryBuilder resourceURI(String resourceURI) {
        seriesSummary.setResourceURI(resourceURI);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SeriesSummary build() {
        return seriesSummary;
    }
}