/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class SeriesDataContainerBuilder {
    //the instance to build
    private SeriesDataContainer seriesDataContainer;

    /**
     * Default constructor to initialize the instance
     */
    public SeriesDataContainerBuilder() {
        seriesDataContainer = new SeriesDataContainer();
    }

    /**
     * The total number of results returned by this call.
     */
    public SeriesDataContainerBuilder count(int count) {
        seriesDataContainer.setCount(count);
        return this;
    }

    /**
     * The requested result limit.
     */
    public SeriesDataContainerBuilder limit(int limit) {
        seriesDataContainer.setLimit(limit);
        return this;
    }

    /**
     * The requested offset (number of skipped results) of the call.
     */
    public SeriesDataContainerBuilder offset(int offset) {
        seriesDataContainer.setOffset(offset);
        return this;
    }

    /**
     * The list of series returned by the call
     */
    public SeriesDataContainerBuilder results(List<Series> results) {
        seriesDataContainer.setResults(results);
        return this;
    }

    /**
     * The total number of resources available given the current filter set.
     */
    public SeriesDataContainerBuilder total(int total) {
        seriesDataContainer.setTotal(total);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SeriesDataContainer build() {
        return seriesDataContainer;
    }
}