/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class StoryListBuilder {
    //the instance to build
    private StoryList storyList;

    /**
     * Default constructor to initialize the instance
     */
    public StoryListBuilder() {
        storyList = new StoryList();
    }

    /**
     * The number of total available stories in this list. Will always be greater than or equal to the "returned" value.
     */
    public StoryListBuilder available(int available) {
        storyList.setAvailable(available);
        return this;
    }

    /**
     * The path to the full list of stories in this collection.
     */
    public StoryListBuilder collectionURI(String collectionURI) {
        storyList.setCollectionURI(collectionURI);
        return this;
    }

    /**
     * The list of returned stories in this collection.
     */
    public StoryListBuilder items(List<StorySummary> items) {
        storyList.setItems(items);
        return this;
    }

    /**
     * The number of stories returned in this collection (up to 20).
     */
    public StoryListBuilder returned(int returned) {
        storyList.setReturned(returned);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public StoryList build() {
        return storyList;
    }
}