/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class StoryBuilder {
    //the instance to build
    private Story story;

    /**
     * Default constructor to initialize the instance
     */
    public StoryBuilder() {
        story = new Story();
    }

    /**
     * A resource list of characters which appear in this story.
     */
    public StoryBuilder characters(CharacterList characters) {
        story.setCharacters(characters);
        return this;
    }

    /**
     * A resource list containing comics in which this story takes place.
     */
    public StoryBuilder comics(ComicList comics) {
        story.setComics(comics);
        return this;
    }

    /**
     * A resource list of creators who worked on this story.
     */
    public StoryBuilder creators(CreatorList creators) {
        story.setCreators(creators);
        return this;
    }

    /**
     * A short description of the story.
     */
    public StoryBuilder description(String description) {
        story.setDescription(description);
        return this;
    }

    /**
     * A resource list of the events in which this story appears.
     */
    public StoryBuilder events(EventList events) {
        story.setEvents(events);
        return this;
    }

    /**
     * The unique ID of the story resource.
     */
    public StoryBuilder id(int id) {
        story.setId(id);
        return this;
    }

    /**
     * The date the resource was most recently modified.
     */
    public StoryBuilder modified(Date modified) {
        story.setModified(modified);
        return this;
    }

    /**
     * A summary representation of the issue in which this story was originally published.
     */
    public StoryBuilder originalissue(ComicSummary originalissue) {
        story.setOriginalissue(originalissue);
        return this;
    }

    /**
     * The canonical URL identifier for this resource.
     */
    public StoryBuilder resourceURI(String resourceURI) {
        story.setResourceURI(resourceURI);
        return this;
    }

    /**
     * A resource list containing series in which this story appears.
     */
    public StoryBuilder series(SeriesList series) {
        story.setSeries(series);
        return this;
    }

    /**
     * The representative image for this story.
     */
    public StoryBuilder thumbnail(Thumbnail thumbnail) {
        story.setThumbnail(thumbnail);
        return this;
    }

    /**
     * The story title.
     */
    public StoryBuilder title(String title) {
        story.setTitle(title);
        return this;
    }

    /**
     * The story type e.g. interior story, cover, text story.
     */
    public StoryBuilder type(String type) {
        story.setType(type);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Story build() {
        return story;
    }
}