/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TextObject 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5588370490932632391L;
    private String language;
    private String text;
    private String type;
    /** GETTER
     * The IETF language tag denoting the language the text object is written in.
     */
    @JsonGetter("language")
    public String getLanguage ( ) { 
        return this.language;
    }
    
    /** SETTER
     * The IETF language tag denoting the language the text object is written in.
     */
    @JsonSetter("language")
    public void setLanguage (String value) { 
        this.language = value;
    }
 
    /** GETTER
     * The text.
     */
    @JsonGetter("text")
    public String getText ( ) { 
        return this.text;
    }
    
    /** SETTER
     * The text.
     */
    @JsonSetter("text")
    public void setText (String value) { 
        this.text = value;
    }
 
    /** GETTER
     * The canonical type of the text object (e.g. solicit text, preview text, etc.).
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * The canonical type of the text object (e.g. solicit text, preview text, etc.).
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
}
 