/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class TextObjectBuilder {
    //the instance to build
    private TextObject textObject;

    /**
     * Default constructor to initialize the instance
     */
    public TextObjectBuilder() {
        textObject = new TextObject();
    }

    /**
     * The IETF language tag denoting the language the text object is written in.
     */
    public TextObjectBuilder language(String language) {
        textObject.setLanguage(language);
        return this;
    }

    /**
     * The text.
     */
    public TextObjectBuilder text(String text) {
        textObject.setText(text);
        return this;
    }

    /**
     * The canonical type of the text object (e.g. solicit text, preview text, etc.).
     */
    public TextObjectBuilder type(String type) {
        textObject.setType(type);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TextObject build() {
        return textObject;
    }
}