/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Thumbnail 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5081663169685117103L;
    private String extension;
    private String path;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("extension")
    public String getExtension ( ) { 
        return this.extension;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("extension")
    public void setExtension (String value) { 
        this.extension = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("path")
    public String getPath ( ) { 
        return this.path;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("path")
    public void setPath (String value) { 
        this.path = value;
    }
 
}
 