/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway.models;

import java.util.*;

public class UrlBuilder {
    //the instance to build
    private Url urlInstance;

    /**
     * Default constructor to initialize the instance
     */
    public UrlBuilder() {
        urlInstance = new Url();
    }

    /**
     * A text identifier for the URL.
     */
    public UrlBuilder type(String type) {
        urlInstance.setType(type);
        return this;
    }

    /**
     * A full URL (including scheme, domain, and path).
     */
    public UrlBuilder url(String url) {
        urlInstance.setUrl(url);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Url build() {
        return urlInstance;
    }
}