/*
 * MarvelComicsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.marvel.gateway;

public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "http://gateway.marvel.com/v1/public";

    //TODO: Replace the referer with an appropriate value
    public static String referer = "TODO: Replace";

    //TODO: Replace the apikey with an appropriate value
    public static String apikey = "";

}
